"""Reproducible synthetic classifier versus its generating rule. No clinical or hardware risk claims."""
import json
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

FEATURES = ["battery_cycle_count", "average_cpu_temp_c", "disk_read_error_rate", "device_age_months"]

def rule_baseline(frame):
    return ((frame.battery_cycle_count > 700) | (frame.average_cpu_temp_c > 88.5) |
            ((frame.device_age_months >= 36) & (frame.disk_read_error_rate > .04))).astype(int)

def generate_data(size=2500, seed=42):
    rng = np.random.default_rng(seed)
    return pd.DataFrame({"battery_cycle_count": rng.integers(10, 950, size),
        "average_cpu_temp_c": rng.uniform(40, 98, size), "disk_read_error_rate": rng.uniform(0, .08, size),
        "device_age_months": rng.integers(1, 48, size)})

def metrics(truth, predicted):
    return {"accuracy": float(accuracy_score(truth, predicted)), "precision": float(precision_score(truth, predicted, zero_division=0)),
            "recall": float(recall_score(truth, predicted, zero_division=0)), "f1": float(f1_score(truth, predicted, zero_division=0))}

def execute_model_training(output_dir=None):
    data = generate_data()
    labels = rule_baseline(data)
    train, test, y_train, y_test = train_test_split(data, labels, test_size=.2, random_state=42, stratify=labels)
    model = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42, n_jobs=1)
    model.fit(train[FEATURES], y_train)
    predicted = model.predict(test[FEATURES])
    report = {"dataset": "Synthetic telemetry; labels are generated by rule_baseline, not observed device failures", "seed": 42,
        "sample_size": len(data), "train_size": len(train), "test_size": len(test), "split": "stratified random holdout; not temporal validation",
        "rule_baseline": metrics(y_test, rule_baseline(test)), "random_forest": metrics(y_test, predicted),
        "limitations": "Rule agreement only. Class probabilities are not calibrated device-failure probabilities. No evidence that ML improves this task."}
    if output_dir:
        out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
        (out / "evaluation.json").write_text(json.dumps(report, indent=2) + "\n")
    return model, report

if __name__ == "__main__":
    _, report = execute_model_training(Path(__file__).resolve().parents[2] / "evidence")
    print(json.dumps(report, indent=2))
