"""Check source syntax, required project evidence files and local Markdown links."""
from pathlib import Path
from urllib.parse import unquote, urlsplit
import ast,json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1]

def main():
    files=subprocess.check_output(['git','ls-files','-co','--exclude-standard','-z'],cwd=ROOT).decode().split('\0')
    files=sorted({name for name in files if name and ((ROOT/name).is_file() or (ROOT/name).is_symlink())})
    errors=[];links=0;python_count=0
    for name in files:
        p=ROOT/name
        if 'node_modules' in p.parts:
            errors.append('Tracked dependency directory/link: '+name);continue
        if p.is_symlink():
            if not p.resolve().is_relative_to(ROOT):errors.append('External symlink: '+name)
            continue
        if p.suffix=='.py':
            try:ast.parse(p.read_text(encoding='utf-8-sig'), filename=name);python_count+=1
            except Exception as exc:errors.append(f'{name}: {exc}')
        if p.suffix=='.pyc':errors.append('Tracked/generated bytecode: '+name)
        if p.suffix=='.md' and p.name not in {'UPSTREAM README.md','commit_log.md'}:
            content=re.sub(r'```.*?```','',p.read_text(),flags=re.S)
            for target in re.findall(r'\]\(([^)]+)\)',content):
                target=target.split(' "')[0].strip('<>')
                if not target or target.startswith('#') or urlsplit(target).scheme:continue
                decoded=unquote(target.split('#')[0])
                resolved=(p.parent/decoded).resolve();links+=1
                if not resolved.is_relative_to(ROOT) or not resolved.exists():errors.append(f'{name}: broken/outside link {target}')
    index=json.loads((ROOT/'docs/project-index.json').read_text())
    for item in index['projects']:
        for name in ['README.md','LAB.md','EVALUATION.md','DEMO SCRIPT.md','CONTRIBUTIONS.md','CHANGELOG.md']:
            if not (ROOT/item['path']/name).is_file():errors.append(f"{item['path']}: missing {name}")
    print(json.dumps({'python_sources':python_count,'local_links':links,'errors':errors},indent=2))
    return bool(errors)

if __name__=='__main__':sys.exit(main())
